# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  #Maintain dependencies for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/PlantUmlViewer/PlantUmlViewer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ExCSS"
      - dependency-name: "Fizzler"
      - dependency-name: "System.Memory"
      - dependency-name: "System.Runtime.CompilerServices.Unsafe"

  #Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
