name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, x86]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Nuget restore solution
      working-directory: PlantUmlViewer\
      run: nuget restore PlantUmlViewer.sln

    - name: MSBuild of solution
      working-directory: PlantUmlViewer\
      run: msbuild PlantUmlViewer.sln /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /m /verbosity:minimal

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v2
      with:
          name: PlantUmlViewer_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
          path: PlantUmlViewer\PlantUmlViewer\bin\${{ matrix.build_configuration }}-${{ matrix.build_platform }}\PlantUmlViewer.dll

    - name: Create release on tagging
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: PlantUmlViewer_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
