name: Continuous Integration

on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, x86]

    steps:
    - run: choco install netfx-4.6.2-devpack

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Nuget restore solution
      working-directory: PlantUmlViewer/
      run: nuget restore PlantUmlViewer.sln

    - name: MSBuild of solution
      working-directory: PlantUmlViewer/
      run: msbuild PlantUmlViewer.sln /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /m /verbosity:minimal

#    - uses: olegtarasov/get-tag@v2.1
#      id: tagName

#    - uses: suisei-cn/actions-download-file@v1
#      id: plantUmlJarFile
#      name: Download PlantUML JAR file
#      with:
#        url: https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar
#        target: build/
#        auto-match: false

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
#          name: PlantUmlViewer_v${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
          name: PlantUmlViewer_${{ matrix.build_platform }}
          path: |
              PlantUmlViewer/PlantUmlViewer/bin/${{ matrix.build_configuration }}-${{ matrix.build_platform }}/PlantUmlViewer.dll
#              build/plantuml-1.2022.5.jar

#    - name: Create release on tagging
#      if: startsWith(github.ref, 'refs/tags/')
#      uses: softprops/action-gh-release@v1
#      with:
#          files: |
#              PlantUmlViewer_v${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
