name: Continuous Integration

on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 4
      matrix:
        #[Release, Debug]
        build_configuration: [Release]
        build_platform: [x64, x86]

    steps:
    - run: choco install netfx-4.6.2-devpack

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Nuget restore solution
      working-directory: PlantUmlViewer/
      run: nuget restore PlantUmlViewer.sln

    - name: MSBuild of solution
      working-directory: PlantUmlViewer/
      run: msbuild PlantUmlViewer.sln /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /m /verbosity:minimal

    - name: Download libraries
      if: matrix.build_configuration == 'Release'
      run: |
        mkdir libraries
        curl -L --url https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar --output libraries/plantuml-1.2022.5.jar
        curl -L --url http://beta.plantuml.net/plantuml-jlatexmath.zip --output libraries\plantuml-jlatexmath.zip
        tar -xf libraries\plantuml-jlatexmath.zip -C libraries
        Remove-Item libraries\plantuml-jlatexmath.zip

    - name: Archive artifacts
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: PlantUmlViewer_${{ github.ref_name }}_${{ matrix.build_platform }}
          path: |
              PlantUmlViewer/PlantUmlViewer/bin/${{ matrix.build_configuration }}-${{ matrix.build_platform }}/PlantUmlViewer.dll
              libraries/

#    - name: Create release on tagging
#      if: startsWith(github.ref, 'refs/tags/')
#      uses: softprops/action-gh-release@v1
#      with:
#          files: |
#              PlantUmlViewer_v${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}
